### ISSUE TITLE
Does not install on Windows10 even with build tools and python

### ISSUE THREAD

**Issue by nektro** [JoshuaWise/integer#9]
https://gist.github.com/nektro/96f301d3d1891451fac0f11416d0d18c

**Comment by JoshuaWise** [comment]
This is not an issue with `integer` itself, it's an issue with [`node-gyp`](https://github.com/nodejs/node-gyp).

**Comment by nektro** [comment]
do you know if [nodejs/node-gyp](https://github.com/nodejs/node-gyp) has a running issue on this? or what i can do to fix it?

**Comment by JoshuaWise** [comment]
@nektro The issue is probably related to how your specific system is configured.

You may need to install [windows-build-tools](https://www.npmjs.com/package/windows-build-tools):

```
npm install --global --production windows-build-tools
```

It's possible you need to configure it with a different version of visual studio:
```
npm install --global --production --vs2015 windows-build-tools node-gyp
```

It's possible that the build system can't find its python dependency:
```
npm install --global --production --vs2015 --add-python-to-path windows-build-tools node-gyp
```

If none of those fix your problem, I would try google searching:
> The imported project "C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V110\Microsoft.Cpp.Default.props" was not found.

**Comment by barbalex** [comment]
@JoshuaWise You saved my ass after spending 3 days chasing ghosts.

```
npm install --global --production --vs2015 windows-build-tools node-gyp
```

_finally_ worked for me.

Please enjoy a beer. Or just having saved a complete stranger's ass :-)
